spring:
  datasource:
    driver-class-name: org.h2.Driver
    platform: h2
    username: sa
    password:
    url: jdbc:h2:~/test;DB_CLOSE_DELAY=-1

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hiberante.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.enable_lazy_load_no_trans: true

    #      javax:
    #        persistence:
    #          schema-generation:
    #            create-source: metadata
    #            scripts:
    #              action: create
    #              create-target: create.sql

    database-platform: org.hibernate.dialect.H2Dialect



